# Frontend Partner — partner.flotteq.fr
upstream frontend_partner {
    server frontend-partner:80;
}

server {
    listen 80;
    listen [::]:80;
    server_name partner.flotteq.fr;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name partner.flotteq.fr;

    ssl_certificate /etc/letsencrypt/live/flotteq.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/flotteq.fr/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    add_header Strict-Transport-Security "max-age=63072000" always;

    access_log /var/log/nginx/partner_access.log main;
    error_log /var/log/nginx/partner_error.log warn;

    location / {
        limit_req zone=general_limit burst=50 nodelay;
        proxy_pass http://frontend_partner;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
